version: '3.4'

services:
  multilayerarchitecture:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Password=@123456789@
      - Kestrel__Certificates__Default__Path=/app/https/certificate.pfx
    ports:
      - "8000:80"
      - "8001:443"